---
- name: Play for deploying website to centos and debian server
  hosts: my_vm_servers
  become: true
  become_method: sudo
  tasks:
    - name: Update repositories cache and install "apache2" package
      ansible.builtin.apt:
        name: "{{ item  }}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - git
      when: ansible_os_family == "Debian"
    
    - name: Restart the web server if a file was changed
      service:
        name: apache2
        state: restarted
      when: ansible_check_mode == False and ansible_os_family == "Debian"
    
    - name: Update repositories cache and install "httpd" package
      ansible.builtin.yum:
        name: 
          - httpd
          - git
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Restart the web server if a file was changed
      service:
        name: httpd
        state: restarted
      when: ansible_check_mode == False and ansible_os_family == "RedHat"

    - name: Check if directory exists
      stat:
        path: /home/temmytope/projects
      register: dir_status

    - name: clone a github repo
      ansible.builtin.git:
        repo: "https://github.com/temmytope88/flex.git"
        dest: /home/temmytope/projects/flex
      when: not dir_status.stat.exists
        

    - name: copy file to var
      ansible.builtin.copy:
        src: /home/temmytope/projects/flex
        dest: /var/www/html
      