#!/bin/bash


#function for installing packages
function install(){
        #echo -e "\nEnter a list of packages to be installed (separated by spaces)\n"
        #read -r -a packages
        sudo apt install $1 -y
}


#function for setting up a new user on the mysql database
function createMysqlUser(){
    # Connect to MySQL and create the new user
    mysql -u root -p$1 -e "CREATE USER '$2'@'localhost' IDENTIFIED BY '$3';"

    # Grant all privileges to the new user
    mysql -u root -p$1 -e "GRANT ALL PRIVILEGES ON *.* TO '$2'@'localhost' WITH GRANT OPTION;"

    # Flush privileges to apply changes
    mysql -u root -p$1 -e "FLUSH PRIVILEGES;"

    echo "New MySQL user '$3' created with all privileges."
}

#function for cloning the php application from git
function cloneFromGit(){
        if [ -d "$2" ]; then
                # Navigate to the target directory
                cd "$2" || exit

                # Fetch updates from the remote repository
                git fetch origin

                # Check if the local repository is up to date
                if git diff --quiet HEAD FETCH_HEAD; then
                        echo "Repository is up to date."
                else
                        echo "Repository is not up to date."
                        # Pull changes from the remote repository
                        git pull
                fi
        else
                # Clone the repository into the target directory
                git clone "$1" "$2"
                if [ $? -eq 0 ]; then
                        echo "Repository cloned successfully into $2"
                else
                        echo "Failed to clone repository"
                fi
        fi

        
}

function moveToApacheFolder(){
        mv $1 $2
        if [ -d "$2" ]; then
                # Move the contents of the source directory to the target directory
                mv -u "$1" "$2"
                if [ $? -eq 0 ]; then
                        echo "Directory moved successfully."
                else
                        echo "Failed to move directory."
                fi
        else
                 mv $1 $2
        fi
}

#update server
echo -e "*********======== About to update server =========********\n"

sudo apt update #update the server

#list of packages to be installed
packages=("apache2" "git")

#looping over the list of packages to be installed
for package in "${packages[@]}"; do
    echo -e "\n==========******** About to install ${package} ********========= \n"  
    install ${package}
done

#setting up mysql database for a new user
mysql_root_password="*.Oluwaseyi88.*"
mysql_user_password="*.Oluwaseyi88.*"
mysql_username=temmytope
createMysqlUser  $mysql_root_password $mysql_username $mysql_user_password

#clone php web application
gitUrl="https://github.com/temmytope88/test"
target_directory="/tmp/test"
cloneFromGit $gitUrl $target_directory

#move the clone app to /var/www/html
www_path=/var/www/html
cloned_path=/tmp/test
moveToApacheFolder $cloned_path $www_path
