#!/usr/bin/bash
NUMBER_OF_ARG=$#

# To check if a file is attached
if [[ $# -eq 0 ]]; then
    echo "error: no file directory indicated"
    exit 1
else
    if [[ $1 == "-n" ]]; then #checking if the argument is -n

        if [[ $# == 3 ]]; then #checking if the -n option comes with a number
            if [[ -e $3 ]]; then
                du -h $3 | sort -hr | head -n $2
            else
                echo "file does not exists"
            fi
        else
            if [[ -e $2 ]]; then
                du -ah $2 | sort -hr | head -n 8
            else
                echo "file does not exist"
            fi
        fi

    elif [[ $1 == "-d" ]]; then #checking if the option is d
        if [[ -e $2 ]]; then
            du -h $2
        else
            echo "file does not exist"
        fi
    else
        echo "error: improper usage"
    fi
fi